###########################################################################
# Docker Compose File
###########################################################################
#
# Your Docker Compose file spins up your application's environment.
# It defines all of the services, network links and volumes to
# be used by your application. Modify this file as required.
#
version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "80:80"
    
  mysql:
    image: mysql
    volumes:
      - ./storage/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    
